import React, { useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import './LegalInfo.css';

export default function LegalInfo() {
  const { hash } = useLocation();

  useEffect(() => {
    if (!hash) return;
    const el = document.getElementById(hash.slice(1));
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }, [hash]);

  return (
    <div className="lg-root">
      <div className="lg-card">
        <Link to="/" className="lg-logo">StyleAI</Link>
        <p className="lg-note">
          StyleAI is a final-year academic thesis project, not a commercial product.
          This page explains, in plain terms, what data the app collects and how it is used.
        </p>

        <section id="privacy" className="lg-section">
          <h2>Privacy Policy</h2>
          <p>
            StyleAI stores the information you provide during registration and onboarding
            (name, email, style preferences, body type, and similar profile details) and the
            wardrobe photos and item details you add. Photos are hosted via Cloudinary; all
            other data is stored in a MongoDB database used only to power your recommendations.
          </p>
          <p>
            Your data is never sold or shared with third parties. It is used solely to generate
            personalized outfit recommendations and to improve the recommendation model as part
            of this thesis research. You can edit or delete your profile and wardrobe data at
            any time from Settings.
          </p>
        </section>

        <section id="terms" className="lg-section">
          <h2>Terms &amp; Conditions</h2>
          <p>
            By creating an account, you agree to use StyleAI for personal, non-commercial
            purposes as part of evaluating this academic project. The recommendations provided
            are generated by an automated system and are offered as styling suggestions only —
            StyleAI makes no guarantee of fitness for any particular purpose or occasion.
          </p>
          <p>
            The service is provided "as is" for demonstration and academic evaluation, without
            warranty of uptime or continued availability.
          </p>
        </section>

        <section id="cookies" className="lg-section">
          <h2>Cookie Policy</h2>
          <p>
            StyleAI uses a single authentication token stored in your browser to keep you
            signed in. No third-party advertising or tracking cookies are used.
          </p>
        </section>

        <Link to="/" className="lg-back">← Back to home</Link>
      </div>
    </div>
  );
}
